"""empty message

Revision ID: 726ef972605b
Revises: 8ba1c6f5e0e9
Create Date: 2023-03-29 04:03:39.622243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726ef972605b'
down_revision = '8ba1c6f5e0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')

    # ### end Alembic commands ###
