"""empty message

Revision ID: 8ba1c6f5e0e9
Revises: 8caebf1fe1b3
Create Date: 2023-03-29 00:59:00.275785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba1c6f5e0e9'
down_revision = '8caebf1fe1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower_following', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower_following', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
